/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface BlindAuctionInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "auctionEnd"
      | "beneficiary"
      | "bid"
      | "getHighBidHandle"
      | "getResult"
      | "revealedWinningBid"
      | "state"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "AuctionRevealed" | "BidSubmitted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "auctionEnd",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "beneficiary",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "bid",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getHighBidHandle",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getResult", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "revealedWinningBid",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "state", values?: undefined): string;

  decodeFunctionResult(functionFragment: "auctionEnd", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "beneficiary",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "bid", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getHighBidHandle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getResult", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "revealedWinningBid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "state", data: BytesLike): Result;
}

export namespace AuctionRevealedEvent {
  export type InputTuple = [winningBid: BigNumberish];
  export type OutputTuple = [winningBid: bigint];
  export interface OutputObject {
    winningBid: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BidSubmittedEvent {
  export type InputTuple = [bidder: AddressLike];
  export type OutputTuple = [bidder: string];
  export interface OutputObject {
    bidder: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BlindAuction extends BaseContract {
  connect(runner?: ContractRunner | null): BlindAuction;
  waitForDeployment(): Promise<this>;

  interface: BlindAuctionInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  auctionEnd: TypedContractMethod<[], [bigint], "view">;

  beneficiary: TypedContractMethod<[], [string], "view">;

  bid: TypedContractMethod<
    [encBid: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  getHighBidHandle: TypedContractMethod<[], [string], "view">;

  getResult: TypedContractMethod<
    [],
    [[boolean, bigint] & { isRevealed: boolean; winningBid: bigint }],
    "view"
  >;

  revealedWinningBid: TypedContractMethod<[], [bigint], "view">;

  state: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "auctionEnd"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "beneficiary"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "bid"
  ): TypedContractMethod<
    [encBid: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getHighBidHandle"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getResult"
  ): TypedContractMethod<
    [],
    [[boolean, bigint] & { isRevealed: boolean; winningBid: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "revealedWinningBid"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "state"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "AuctionRevealed"
  ): TypedContractEvent<
    AuctionRevealedEvent.InputTuple,
    AuctionRevealedEvent.OutputTuple,
    AuctionRevealedEvent.OutputObject
  >;
  getEvent(
    key: "BidSubmitted"
  ): TypedContractEvent<
    BidSubmittedEvent.InputTuple,
    BidSubmittedEvent.OutputTuple,
    BidSubmittedEvent.OutputObject
  >;

  filters: {
    "AuctionRevealed(uint64)": TypedContractEvent<
      AuctionRevealedEvent.InputTuple,
      AuctionRevealedEvent.OutputTuple,
      AuctionRevealedEvent.OutputObject
    >;
    AuctionRevealed: TypedContractEvent<
      AuctionRevealedEvent.InputTuple,
      AuctionRevealedEvent.OutputTuple,
      AuctionRevealedEvent.OutputObject
    >;

    "BidSubmitted(address)": TypedContractEvent<
      BidSubmittedEvent.InputTuple,
      BidSubmittedEvent.OutputTuple,
      BidSubmittedEvent.OutputObject
    >;
    BidSubmitted: TypedContractEvent<
      BidSubmittedEvent.InputTuple,
      BidSubmittedEvent.OutputTuple,
      BidSubmittedEvent.OutputObject
    >;
  };
}
