/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ConfidentialCounterInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "decrement"
      | "getCountHandle"
      | "increment"
      | "owner"
      | "resetIfOver"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CounterDecremented"
      | "CounterIncremented"
      | "CounterReset"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "decrement",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getCountHandle",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "increment",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "resetIfOver",
    values: [BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "decrement", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getCountHandle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "increment", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "resetIfOver",
    data: BytesLike
  ): Result;
}

export namespace CounterDecrementedEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CounterIncrementedEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CounterResetEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ConfidentialCounter extends BaseContract {
  connect(runner?: ContractRunner | null): ConfidentialCounter;
  waitForDeployment(): Promise<this>;

  interface: ConfidentialCounterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  decrement: TypedContractMethod<
    [encAmount: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  getCountHandle: TypedContractMethod<[], [string], "view">;

  increment: TypedContractMethod<
    [encAmount: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  resetIfOver: TypedContractMethod<
    [encThreshold: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "decrement"
  ): TypedContractMethod<
    [encAmount: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getCountHandle"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "increment"
  ): TypedContractMethod<
    [encAmount: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "resetIfOver"
  ): TypedContractMethod<
    [encThreshold: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "CounterDecremented"
  ): TypedContractEvent<
    CounterDecrementedEvent.InputTuple,
    CounterDecrementedEvent.OutputTuple,
    CounterDecrementedEvent.OutputObject
  >;
  getEvent(
    key: "CounterIncremented"
  ): TypedContractEvent<
    CounterIncrementedEvent.InputTuple,
    CounterIncrementedEvent.OutputTuple,
    CounterIncrementedEvent.OutputObject
  >;
  getEvent(
    key: "CounterReset"
  ): TypedContractEvent<
    CounterResetEvent.InputTuple,
    CounterResetEvent.OutputTuple,
    CounterResetEvent.OutputObject
  >;

  filters: {
    "CounterDecremented()": TypedContractEvent<
      CounterDecrementedEvent.InputTuple,
      CounterDecrementedEvent.OutputTuple,
      CounterDecrementedEvent.OutputObject
    >;
    CounterDecremented: TypedContractEvent<
      CounterDecrementedEvent.InputTuple,
      CounterDecrementedEvent.OutputTuple,
      CounterDecrementedEvent.OutputObject
    >;

    "CounterIncremented()": TypedContractEvent<
      CounterIncrementedEvent.InputTuple,
      CounterIncrementedEvent.OutputTuple,
      CounterIncrementedEvent.OutputObject
    >;
    CounterIncremented: TypedContractEvent<
      CounterIncrementedEvent.InputTuple,
      CounterIncrementedEvent.OutputTuple,
      CounterIncrementedEvent.OutputObject
    >;

    "CounterReset()": TypedContractEvent<
      CounterResetEvent.InputTuple,
      CounterResetEvent.OutputTuple,
      CounterResetEvent.OutputObject
    >;
    CounterReset: TypedContractEvent<
      CounterResetEvent.InputTuple,
      CounterResetEvent.OutputTuple,
      CounterResetEvent.OutputObject
    >;
  };
}
