/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  TFHEErrors,
  TFHEErrorsInterface,
} from "../../../../fhevm-contracts/contracts/utils/TFHEErrors";

const _abi = [
  {
    inputs: [],
    name: "TFHESenderNotAllowed",
    type: "error",
  },
] as const;

export class TFHEErrors__factory {
  static readonly abi = _abi;
  static createInterface(): TFHEErrorsInterface {
    return new Interface(_abi) as TFHEErrorsInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): TFHEErrors {
    return new Contract(address, _abi, runner) as unknown as TFHEErrors;
  }
}
